# Site settings
baseurl = "https://www.toppers.com.cn/en"
languageCode = "en-us"
title = "TPPPERS"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "logo.png"
    product = "Product"
    service = "Service"
    company = "Company"
    contact = "Contact"

  # Hero section
  [params.hero]
    enable = true
    notext = false
    title = "Lose Yourself in Music"
    description = "Intelligent digital–control One-key Noise Cancellation Free your hands with digital-control box integrated answer-call key LED lights dynamically show your battery level"

  [params.carousel]
    enable = false

  #Product section
  [params.product]
    enable = true
    title = "product"
    subtitle = "A nice day starts with TOPPERS"

  [[params.product.row]]

    [[params.product.row.list]]
      icon = "iconfont tp-earphones"
      title = "Noise Cancelling Earphones"
      description = ""
      modalID = 1

    [[params.product.row.list]]
      icon = "iconfont tp-watch"
      title = "Children's Smart Watch"
      description = ""
      modalID = 2
    
    [[params.product.row.list]]
      icon = "iconfont tp-more"
      title = "More"
      description = ""
      modalID = 3

# service section
  [params.service]
    enable = true
    center = true
    title = "Service"
    subtitle = "TOPPERS provide you with the best UE."
    [[params.service.members]]
      img = "1.png"
      name = "Smart Speaker"
      social = [
        ["fa-android", "http://static.toppers.com.cn/app/Toppers%20S1-v1.0.apk"],
        ["fa-apple", "https://itunes.apple.com/cn/app/toppers-s1/id1348745313?mt=8"],
      ]

    [[params.service.members]]
      img = "2.png"
      name = "Earphone Translator"
      social = [
        ["fa-android", "http://static.toppers.com.cn/app/TOPPERS%20E1-v2.1.2.apk"],
        ["fa-apple", "https://itunes.apple.com/cn/app/%E5%B0%8F%E6%B7%98%E6%99%BA%E8%83%BD%E8%80%B3%E6%9C%BA/id1335517514?l=en&mt=8"],
      ]

    [[params.service.members]]
      img = "3.png"
      name = "Children's Smart Watch"
      social = [
        ["fa-android", "http://static.toppers.com.cn/app/Toppers%20W1-v1.0.apk"],
        ["fa-apple", "https://itunes.apple.com/cn/app/小淘儿童手表/id1347040276?l=en&mt=8"],
      ]

 # company section
  [params.company]
    enable = true
    title = "Company"
    subtitle = "For other services, please visit TOPPERS"
  [[params.company.row]]

    [[params.company.row.list]]
      icon = "iconfont tp-about"
      title = "About Us"
      description = "Boxin Investing & Holdings Co. Ltd is a high-tech enterprise who is dedicated to producing top quality, intelligent products and solutions."
    

    [[params.company.row.list]]
      icon = "iconfont tp-technology"
      title = "Product Concept"
      description = "Based on AI (Artificial Intelligence) and Big Data, it provides smarter and more personalized products; Based on IoT and Pervasive Networking Technology, it makes products more interconnected and sharable; With mobile network, it makes products more portable and practical."
      

    [[params.company.row.list]]
      icon = "iconfont tp-development"
      title = "R&D Centre"
      description = "Boxin Investing & Holdings Co. Ltd planned to set up branches in Beijing, Suzhou, Shenzhen, America and Singapore to make full use of the local high-quality resources and introduce leading technologies to bring benefit to our users."
    

  # Contact section
  [params.contact]
    enable = true
    company = "Boxin Smartcom (Suzhou) Sci&Tech Co.Ltd"
    address = [ 
      ["Beijing Address:","Floor 12 Gendale Center,No 91 Jianguo Road,Chaoyang District,Beijing"],
      ["Suzhou Address:","Room 706,Floor 7,No 288 Jinke Street,Suzhou City"],
    ]
    phone = "Phone: &nbsp; 010-58702900"
    email = "Email: &nbsp; kefu@boxinholding.com"
    call = [["call.png","400-000-1656"]]

  # Footer section
  [params.footer]
    enable = true
    copyright = "Copyright © 2017-2018 Boxin Smartcom (Suzhou) Sci&Tech Co.Ltd All rights reserved"

    [[params.footer.social]]
      icon = "fa-weixin"
      link = "javascript:void(0);"
      title = "wechat"

    [[params.footer.social]]
      icon = "fa-weibo"
      link = "javascript:void(0);"
      title = "sina weibo"

